apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ckk43848
  namespace: ckk43848
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ckk43848
  destination:
    name: argus
    namespace: ckk43848
  source:
    path: apps
    repoURL: https://github.com/ZohebShaikh/pollux-deployment
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
